### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by josemartins88** [josemartins88/playground-api#3]
- [ ] Best practices for building node packages (test within docker build?)
- [ ] Possibly publish to AWS container registry
- [ ] Deploy to AWS EC2 instance
